@echo off
REM è¨ï∂éöÇ…ïœä∑

SET STR=TeSt STrINg

SET STR=%STR:A=a%
SET STR=%STR:B=b%
SET STR=%STR:C=c%
SET STR=%STR:D=d%
SET STR=%STR:E=e%
SET STR=%STR:F=f%
SET STR=%STR:G=g%
SET STR=%STR:H=h%
SET STR=%STR:I=i%
SET STR=%STR:J=j%
SET STR=%STR:K=k%
SET STR=%STR:L=l%
SET STR=%STR:M=m%
SET STR=%STR:N=n%
SET STR=%STR:O=o%
SET STR=%STR:P=p%
SET STR=%STR:Q=q%
SET STR=%STR:R=r%
SET STR=%STR:S=s%
SET STR=%STR:T=t%
SET STR=%STR:U=u%
SET STR=%STR:V=v%
SET STR=%STR:W=w%
SET STR=%STR:X=x%
SET STR=%STR:Y=y%
SET STR=%STR:Z=z%

ECHO %STR%

REM ëÂï∂éöÇ…ïœä∑

SET STR2=TeSt STrINg 2

SET STR2=%STR2:a=A%
SET STR2=%STR2:b=B%
SET STR2=%STR2:c=C%
SET STR2=%STR2:d=D%
SET STR2=%STR2:e=E%
SET STR2=%STR2:f=F%
SET STR2=%STR2:g=G%
SET STR2=%STR2:h=H%
SET STR2=%STR2:i=I%
SET STR2=%STR2:j=J%
SET STR2=%STR2:k=K%
SET STR2=%STR2:l=L%
SET STR2=%STR2:m=M%
SET STR2=%STR2:n=N%
SET STR2=%STR2:o=O%
SET STR2=%STR2:p=P%
SET STR2=%STR2:q=Q%
SET STR2=%STR2:r=R%
SET STR2=%STR2:s=S%
SET STR2=%STR2:t=T%
SET STR2=%STR2:u=U%
SET STR2=%STR2:v=V%
SET STR2=%STR2:w=W%
SET STR2=%STR2:x=X%
SET STR2=%STR2:y=Y%
SET STR2=%STR2:z=Z%

ECHO %STR2%



PAUSE
